### ISSUE TITLE
Add styling for base-line y grid line

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#252]
When chart contains value(s) below 0, the x-axis will be displayed at the bottom, not at y=0. In this case, a grid line is placed on y=0. This line is styled as:
```css
g.base-line line {
  stroke: #000;
}
```

...which of course looks like cr*p. It should not :smile:
