### ISSUE TITLE
Chart colors do not support css variables (themes) or scoping

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/green#357]
Billboard.js extracts colors from a background image using the `.bb-color-pattern` selector defined like this:

```css
.bb-color-pattern {
    background-image: url('#45B400;#0092E1;#FFB400;#D81A1A;#4F2C99;#8AAEC7;#FF7E5A;#898EFE;#FFAC35;#70B0FF;');
}
```

Billboard can't find the pattern if it's being scoped with something like this:

```css
.use-green .bb-color-pattern {
    background-image: url('#45B400;#0092E1;#FFB400;#D81A1A;#4F2C99;#8AAEC7;#FF7E5A;#898EFE;#FFAC35;#70B0FF;');
}
```

It's not possible to use css variable either so different themes would need to override the default and charts would have to be redrawn when switching themes.

Best option would be to use pure css to style the different svg element using svg fill and stroke properties together css variables as it would allow switching between themes as well as more dynamic ways of assigning colors, gradients etc.
