### ISSUE TITLE
Dropdown: White text on white background.

### ISSUE THREAD

**Issue by R0tenur** [sebgroup/green#696]
Text color is inherited by parent wich results in white text on white background when parent has class `.bg-dark`

```html
<div class="bg-dark">
   <ngg-dropdown
          [(value)]="selectedLanguage"
          [options]="languages"
          (valueChange)="setLanguage()"
    ></ngg-dropdown>
</div>
```

Results in: 
![bild](https://user-images.githubusercontent.com/12293736/211780784-f7dfc7de-adc8-40fa-8efa-1ea259f7fe73.png)

Tempfix for our projects is currently:
```css
ngg-dropdown .popover-dropdown ul[role="listbox"] [role="option"] { color: #000; }
```
